name: CI/CD asdsad
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel twine
          pip install -r requirements.txt
          pip install -e .

      - name: Build distribution packages
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v2
        with:
          username: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          distribution: dist/*

      - name: Create Git tag
        run: |
          git tag v$VERSION
          git push --tags

      - name: Commit tag change
        run: |
          git commit -am "Bump version to $VERSION"
          git push
