name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Git
        run: sudo apt-get install -y git

      - name: Check for version bump
        id: check_version_bump
        run: |
          echo "::set-output name=bump::$(git log -1 --pretty=%B | grep -q '\[bump\]' && echo true || echo false)"

      - name: Bump version and create tag
        if: steps.check_version_bump.outputs.bump == 'true' && github.event_name == 'push'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          python bump_version.py | xargs git tag
          git push --tags

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel setuptools_scm twine
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.1
        with:
          username: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          distribution: dist/*

      - name: Create Git tag
        run: |
          git tag v$VERSION
          git push --tags

      - name: Commit tag change
        run: |
          git commit -am "Bump version to $VERSION"
          git push
